### ISSUE TITLE
IntoIter

### ISSUE THREAD

**Issue by tychota** [rust-unofficial/too-many-lists#107]
When doing https://rust-unofficial.github.io/too-many-lists/second-into-iter.html, clippy was politely mad at me.

```
defining a method called `into_iter` on this type; consider implementing the `std::iter::IntoIterator` trait or choosing a less ambiguous name

note: #[warn(clippy::should_implement_trait)] on by default
help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#should_implement_trait
```

I'm completly new to rust but would that make sense ?

```diff
pub struct IntoIter<T>(List<T>);

-impl<T> List<T> {
+impl<T> std::iter::IntoIterator for List<T> {
+    type Item = T;
+    type IntoIter = IntoIter<T>;

    pub fn into_iter(self) -> IntoIter<T> {
        IntoIter(self)
    }
}
```

If not why ?

**Comment by dospro** [comment]
I was wondering the same thing. This raised another question: Is there any difference on using `std::iter::IntoIterator` standard trait instead of just implementing `into_iter` alone?  
Does a `for` loop expects the `IntoIterator` trait so you won't need to explicitly call the `into_iter` method?

**Comment by Gankra** [comment]
I just didn't want to get into talking about the IntoIterator trait at this point in the book. A bit too much of a distraction (and I don't expect users to have clippy setup since this is a beginner text).

The clippy lint is ~correct that impling the trait is better. It lets you pass your type directly to a for loop, and most methods expecting an Iterator (because they usually request an IntoIterator to be slightly more convenient).

But yeah I'm fine with omitting the detail, especially because I don't want to mislead anyone into thinking IntoIterator is somehow necessary.
