### ISSUE TITLE
Can I write japanese translation?

### ISSUE THREAD

**Issue by stmtk1** [rust-unofficial/too-many-lists#196]
I think there are many Japanese  reader of this article, but there is no Japanese translated article.

**Comment by Gankra** [comment]
If you want to, I don't see why not?

**Comment by stmtk1** [comment]
I can't guess overall of previous sentence. Can you write sentence with no missing word?

**Comment by tatsuya6502** [comment]
Please correct me if I am wrong, but I believe the full sentences would be the followings:

"If you want to, you can translate this book into Japanese. Because I don't see any reason why you can't."

* * *

Let me introduce myself. I am a member of a GitHub organization [rust-lang-ja](https://github.com/rust-lang-ja/) and an administrator of a Japanese Rust community called [rust-jp](https://rust-jp.slack.com/) ([The registration form](http://rust-jp.herokuapp.com/)).

We are maintaining some Japanese translations of Rust documents at the GitHub organization. Please let me know if you want us to do any or all of the followings:

- Review your Japanese translation.
- Publish the translated book at https://doc.rust-jp.rs web site. (e.g. https://doc.rust-jp.rs/too-many-lists)
- Setup CI to build the book automatically on every git commit.

**Comment by Gankra** [comment]
Just confirming: yes you can write a translation.
