### ISSUE TITLE
6.1 reference to ourselves inside ourselves

### ISSUE THREAD

**Issue by Kryptos-FR** [rust-unofficial/too-many-lists#203]
> We just committed a cardinal Rust sin: we stored a reference to ourselves inside ourselves.

I'm recently starting with Rust and I don't understand what that means in that context. What is *ourselves* here (which type)?

I'm reading over and over `pop` and `push` implementations and it is not obvious to me where the issue lies. A little diagram or a few more sentences would be welcome.

----

> As soon as we tried to use our list, everything quickly fell apart. When we call push or pop, we promptly store a reference to ourselves in ourselves and become trapped. 

It is especially puzzling since the error doesn't seem to be related to *storing reference* at all. A small change to the code to make both method no-op still give the exact same 11 errors:

```rust
impl<'a, T: Default> List<'a, T> {
    pub fn push(&'a mut self, elem: T) {
    }

    pub fn pop(&'a mut self) -> Option<T> {
        Some(Default::default())
    }
}
```

What am I missing? Where does the *store* occur?

**Comment by Gankra** [comment]
Rust doesn't actually "know" you stored a reference to yourself, but the signature of the function *itself* is essentially telling it that. This is hard to explain reasonably because the signature we've give it is essentially gibberish (or at least, never makes sense to use in practice), so I didn't want to dwell on it much.

**Comment by Gankra** [comment]
(I changed my mind, the next update will have more details)
