### ISSUE TITLE
Publish the pretty version

### ISSUE THREAD

**Issue by bestouff** [rust-unofficial/too-many-lists#49]
http://cglab.ca/~abeinges/blah/too-many-lists contains an outdated version (e.g. the code still uses nightly for `#[feature]`). Please update.

**Comment by edunham** [comment]
Thanks for the heads up about this! Since Gankro is the only person with access to that web space and he's no longer able to be actively involved with this project, I'm going to close this issue in favor of publication to GitHub pages (see https://github.com/rust-unofficial/too-many-lists/issues/39)
